#!/bin/bash
set -euo pipefail

# Wait for SSH key to be generated by target container
echo "Waiting for SSH key..."
for i in $(seq 1 30); do
    if [ -f /ssh-keys/id_ed25519 ]; then
        break
    fi
    sleep 1
done

# Setup SSH for the runner
mkdir -p ~/.ssh
cp /ssh-keys/id_ed25519 ~/.ssh/id_ed25519
chmod 600 ~/.ssh/id_ed25519

# Trust the target host
ssh-keyscan -H target >> ~/.ssh/known_hosts 2>/dev/null

# Wait for target SSH to be ready
echo "Waiting for SSH..."
for i in $(seq 1 30); do
    if ssh -o ConnectTimeout=2 deploy@target "echo ok" >/dev/null 2>&1; then
        echo "SSH connection ready"
        break
    fi
    if [ "$i" -eq 30 ]; then
        echo "FATAL: SSH connection to target failed after 30 attempts"
        exit 1
    fi
    sleep 1
done

# Clean up previous deploy output
ssh deploy@target "rm -rf /opt/deploy_to/{releases,current,shared}"

# Install project dependencies
cd /app
yarn install --frozen-lockfile 2>&1

# Run the tests
npx mocha test/e2e/deploy.test.js --timeout 120000
