name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          node-version: 18
      - run: yarn install --frozen-lockfile
      - run: yarn lint

  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker compose -f test/e2e/docker-compose.yml up --build --abort-on-container-exit --exit-code-from runner
